CREATE TABLE artists (
    id SERIAL PRIMARY KEY,
    mbid VARCHAR(50) UNIQUE,
    name TEXT NOT NULL
);

CREATE TABLE albums (
    id SERIAL PRIMARY KEY,
    artist_id INT REFERENCES artists(id),
    mbid VARCHAR(50) UNIQUE,
    title TEXT NOT NULL,
    release_date DATE
);

CREATE TABLE songs (
    id SERIAL PRIMARY KEY,
    album_id INT REFERENCES albums(id),
    mbid VARCHAR(50) UNIQUE,
    title TEXT NOT NULL,
    track_number INT,
    length INT
);

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE user_role AS ENUM ('user', 'admin');
    END IF;
END$$;

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    role user_role DEFAULT 'user'
);


ALTER TABLE artists ADD COLUMN IF NOT EXISTS DateAdded TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE albums ADD COLUMN IF NOT EXISTS DateAdded TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE albums ADD COLUMN IF NOT EXISTS AlbumCoverLink TEXT;

ALTER TABLE songs ADD COLUMN IF NOT EXISTS DateAdded TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE artists ADD COLUMN IF NOT EXISTS Country VARCHAR(100);
ALTER TABLE artists ADD COLUMN IF NOT EXISTS Founded DATE;
ALTER TABLE artists ADD COLUMN IF NOT EXISTS Disbanded DATE;

